
sudo: false
language: python
python: '3.5'
env:
  global:
    secure: wItDlPEpIoLfXFZqqDO5btqSjuOXv3JammJ2IT0GzHbYjH3PBbsYf8C+c07gxoFOaqOaRpcThSF8+5GiGPH7M8aCW9kGg+cOeNqF+1M/o2SkxrpKfPTQHNnDnOKGgmBLdEy8OdQT5j2Wkt2RIP0btffAi21L7SCYpMli070n6TtWG/L0AXVAm3dF/vy40PinlfKtsONAqqQTOKJZexxIKXhnvSS3cRoHHC1XZdmag3CSXk5r9cXT8kWjAcaL8CBA1ekwxXHs64taeRZBzb+EQWKdrkEqbpy+iVygvUJJsjI3VwzBJa/nkcof4lTJNimtg6NHiidOlge7VTL6sSJ8yn+thhYTJ9A/d7H3s07dJlUH/OLJKDPUeCv0WXcfM/sSAGiRqeHCIldw5Y31E4zV7tM3H81uae9NoS3AsUnqmE/uk68SU80d+0PR0glMj4aTEOWt0gmMvvXfcA7IeMY5eNkoJn39oynf2X17JAnc5+dtnWDwbRejkTzJzFcZR8D2M49rQaKtoGW7DxRbBmezq+PjkoxIhKWNsQUg6Otn0mEM81y43RQ2aG0lERPCe10RWHalr9OgZx3+rvPqBqTjlzYASCtYFMkLkYi5OB50gYzlEHdkl787JBPrlt+CNQYT3yUBMIQxI69P4XODoXVJ9Mz2ryDbWb0v2aGOB7MXIYQ=
script:
- git config user.name "tuanpmt"
- git config user.email "tuanpm@live.com"
- git remote add gh-token "https://${GH_TOKEN}@github.com/esp8266vn/esp8266.vn.git"
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages
- pip install mkdocs -U
- pip install git+git://github.com/exaroth/mdx_custom_span_class.git
- mkdocs gh-deploy -v --clean --remote-name gh-token
